### PR TITLE
First run for bitcoin client v0.16.0 on shadow version v1.12.0

### PR DESCRIPTION
**Pull request by ygnkim**
I have updated CMakeLists.txt, sample shadow configuration (resource/example.xml) and README.
I have uploaded a necessary patch for bitcoin repository(DisableSanityCheck.patch) and python script tool for running multi-node experiments(tools/run_multinode_experiment.py).

It seems to be working when i run tests on Ubuntu 14.04.5 LTS.

Tests on Ubuntu 16.04 LTS were failed due to the unexpected segfault errors as i already have mentioned on shadow-support mailing list.

### CODE REVIEW

**Comment by robgjansen** [comment]
FYI, I want to merge this but I'm waiting until I get some time to build and run it on my machine first just to test it out. Thanks for being patient!

**Comment by rickyyx** [comment]
Anyway I can stay updated for this Ubuntu16.04 segfault error? Will this be a tracking issue?

I ran into the same issue on Ubuntu16.04, and tested successfully on my Ubuntu14.05 following steps in the commit.

**Comment by ygnkim** [comment]
Hello, I (personally) have a plan to look into the bitcoin running on the shadow and resolve several implementation issues including the one you have mentioned. But, currently, I'm not tracking the issue, and I don't know exactly when I have time to look into it.

**Comment by robgjansen** [comment]
Hey, over the last 2 days I've been trying to upgrade and existing VM to test this pull request so I can merge it. I ran into issues and it looks like I'll have to do a fresh install. I'm planning to install Ubuntu 18.04.1 LTS and will report my results here.

(I spend my dev time on Shadow core and the Tor plugin, so AFAIK @ygnkim is the primary expert here.)

**Comment by rickyyx** [comment]
@robgjansen @ygnkim 
Really appreciate your reply and work into this!

**Comment by rickyyx** [comment]
I noticed that in the current master, there is documentation about how to run a more realistic example with pre-downloaded chain information. 

However, @ygnkim any idea how I can run a more realistic example with the new commits?

**Comment by ygnkim** [comment]
@githubxxcc 
I'm sorry for late reply.

I can't remember the exact steps i have followed, but it was not that difficult to use pre-downloaded chain information described as https://github.com/shadow/shadow-plugin-bitcoin/wiki#more-realistic-examples.
Since my branch does not use shadow-bitcoind, i looked at its code (including tools/make_symlinks.sh) and manually executed the required steps.

By the way, when i use realistic blockchain data, i have encountered errors related to blockchain timestamp. So, i updated the default time at https://github.com/shadow/shadow/blob/master/src/main/core/support/shd-definitions.h#L73.

**Comment by robgjansen** [comment]
I'm going to go ahead and merge this, and assume that any fixes that might be needed can be applied later.

Thank you for your contribution @ygnkim and sorry I took so very very long!

**Pull request merged**
